(fix) ci package publish

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,8 +2,8 @@ variables:
   GIT_SUBMODULE_STRATEGY: recursive
 
 stages:
-  - deploy
   - prepare
+  - deploy
 
 before_script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
@@ -65,7 +65,7 @@ lint:
 push_composer_package_dev:
   stage: deploy
   when: manual
-  image: docker:24.0.5
+  image: curlimages/curl:latest
   services:
     - docker:24.0.5-dind
   variables:
@@ -74,8 +74,18 @@ push_composer_package_dev:
     DOCKER_TLS_CERTDIR: "/certs"
     DOCKER_DRIVER: overlay2
     DOCKER_HOST: "tcp://docker:2376"
+    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
   script:
-    - apk add curl
-    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=dev "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
-  tags:
-    - docker
+    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
+    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
+    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
+    - code=$(echo "$response" | tail -n 1)
+    - body=$(echo "$response" | head -n 1)
+    # Output state information
+    - if [ $code -eq 201 ]; then
+        echo "Package created - Code $code - $body";
+      else
+        echo "Could not create package - Code $code - $body";
+        exit 1;
+      fi
+
